out_dir: results
metric_best: accuracy
metric_agg: argmax
wandb:
  use: False
  project: ACL-ARC
dataset:
  format: PyG-ACL-ARC
  name: subset
  task: edge
  task_type: classification
  transductive: True
  node_encoder: False
  node_encoder_name: TypeDictNode+RWSE
  node_encoder_num_types: 21
  node_encoder_bn: False
  edge_encoder: False
  edge_encoder_name: TypeDictEdge
  edge_encoder_num_types: 4
  edge_encoder_bn: False
posenc_RWSE:
  enable: False
  kernel:
    times_func: range(1,21)
  model: Linear
  dim_pe: 28
  raw_norm_type: BatchNorm
train:
  mode: custom
  batch_size: 32
  eval_period: 1
  ckpt_period: 100
model:
  type: compgcn
  edge_decoding: concat
  loss_fun: cross_entropy
  graph_pooling: add
gnn:
  head: relation_pred
  layer_type: rgcn
  layers_mp: 6
  layers_pre_mp: 3
  layers_post_mp: 3
  dim_inner: 32
  act: relu
  dropout: 0.0
  agg: mean
  normalize_adj: False
  ffn: True
  residual: True
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 1e-5
  base_lr: 0.001
  max_epoch: 40
  scheduler: cosine_with_warmup
  num_warmup_epochs: 50
  min_lr: 1e-6
